---
  # File for grid search in Hyperparameters
  common:
    train_mode: 'hp_search'
    ckpt_save_path: 'hp_ckpts/' # Change to Google Drive link if trained on Colab.
    num_epochs: 30
    train_data_path: 'data-bin/trainingset.npy'
    test_data_path: 'data-bin/testingset.npy'
    model_type: 'cnn'
    hp: 
      batch_size: [64, 128, 256, 512, 1024]
      lr: [0.005, 0.001, 0.0005, 0.0001]
      schedule: [0] # Enable lr_scheduler at 'schedule' epoch
      gamma: [0.1, 0.5] # lr_scheduler's 'gamma' parameter